CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department VARCHAR(40) NOT NULL,
    name VARCHAR(50) NOT NULL,
    position VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    active VARCHAR(1) NOT NULL DEFAULT 'Y',
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_employees_department_name UNIQUE (department, name),
    CONSTRAINT ck_employees_department CHECK (
        department IN ('NURSING', 'ADMINISTRATION', 'LABORATORY')
    ),
    CONSTRAINT ck_employees_active CHECK (active IN ('Y', 'L', 'N'))
);

CREATE INDEX idx_employees_department_active
    ON employees (department, active);
