CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    name VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    username VARCHAR(50) NOT NULL,
    CONSTRAINT uk_admins_username UNIQUE (username),
    CONSTRAINT ck_admins_role CHECK (role IN ('ADMIN', 'SUPER_ADMIN'))
);

CREATE TABLE doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active CHAR(1) DEFAULT 'Y' NOT NULL,
    birth_date DATE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    department VARCHAR(40) NOT NULL,
    display_order INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_doctors_department_name UNIQUE (department, name),
    CONSTRAINT ck_doctors_active CHECK (active IN ('Y', 'L', 'N')),
    CONSTRAINT ck_doctors_department CHECK (
        department IN (
            'ENT',
            'INTERNAL_MEDICINE',
            'ORTHOPEDICS',
            'GENERAL_SURGERY',
            'NEUROSURGERY',
            'REHABILITATION_MEDICINE'
        )
    )
);

CREATE INDEX idx_doctors_department_active ON doctors (department, active);

CREATE TABLE doctor_available_days (
    doctor_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    CONSTRAINT uk_doctor_available_days UNIQUE (doctor_id, day_of_week),
    CONSTRAINT fk_doctor_available_days_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT ck_doctor_available_days_day CHECK (
        day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    )
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department VARCHAR(40) NOT NULL,
    name VARCHAR(50) NOT NULL,
    position VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    active CHAR(1) DEFAULT 'Y' NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_employees_department_name UNIQUE (department, name),
    CONSTRAINT ck_employees_active CHECK (active IN ('Y', 'L', 'N')),
    CONSTRAINT ck_employees_department CHECK (
        department IN ('NURSING', 'ADMINISTRATION', 'LABORATORY')
    )
);

CREATE INDEX idx_employees_department_active ON employees (department, active);

CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email VARCHAR(254),
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20),
    privacy_agreed BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT ck_inquiries_status CHECK (status IN ('RECEIVED', 'IN_PROGRESS', 'ANSWERED'))
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date DATE NOT NULL,
    appointment_time TIME(0) WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    patient_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    privacy_agreed BOOLEAN NOT NULL,
    reservation_number VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    symptom TEXT,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    doctor_id BIGINT NOT NULL,
    admin_memo TEXT,
    CONSTRAINT uk_reservations_number UNIQUE (reservation_number),
    CONSTRAINT uk_reservations_doctor_schedule UNIQUE (
        doctor_id,
        appointment_date,
        appointment_time
    ),
    CONSTRAINT fk_reservations_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT ck_reservations_status CHECK (
        status IN ('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')
    )
);

CREATE INDEX idx_reservations_date_status ON reservations (appointment_date, status);
CREATE INDEX idx_reservations_phone ON reservations (phone_number);
